@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package panda.leatherworks.common.compat;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;