@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package panda.leatherworks.common.network.message;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;